### ISSUE TITLE
不支持 ollama v0.12.10

### ISSUE THREAD

**Issue by ABC-0101** [Nuo27/Potplayer-Ollama-Translate#3]

**Comment by Nuo27** [comment]
@ABC-0101 测试了0.12.10是能够正常使用的，检查一下有没有准确配置插件

**Comment by ABC-0101** [comment]
ollama serve &
time=2025-11-11T19:01:41.043+08:00 level=INFO source=routes.go:1525 msg="server config" env="map[CUDA_VISIBLE_DEVICES:GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 GGML_VK_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://0.0.0.0:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:E:\\Ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_REMOTES:[ollama.com] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES:]"
time=2025-11-11T19:01:41.058+08:00 level=INFO source=images.go:522 msg="total blobs: 22"
time=2025-11-11T19:01:41.060+08:00 level=INFO source=images.go:529 msg="total unused blobs removed: 0"
time=2025-11-11T19:01:41.062+08:00 level=INFO source=routes.go:1578 msg="Listening on [::]:11434 (version 0.12.10)"
time=2025-11-11T19:01:41.063+08:00 level=INFO source=runner.go:67 msg="discovering available GPUs..."
time=2025-11-11T19:01:41.076+08:00 level=INFO source=server.go:400 msg="starting runner" cmd="E:\\Ollama\\ollama.exe runner --ollama-engine --port 6092"
time=2025-11-11T19:01:41.337+08:00 level=INFO source=server.go:400 msg="starting runner" cmd="E:\\Ollama\\ollama.exe runner --ollama-engine --port 6099"
time=2025-11-11T19:01:41.577+08:00 level=INFO source=server.go:400 msg="starting runner" cmd="E:\\Ollama\\ollama.exe runner --ollama-engine --port 6107"
time=2025-11-11T19:01:42.193+08:00 level=INFO source=types.go:42 msg="inference compute" id=GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 filter_id="" library=CUDA compute=8.6 name=CUDA0 description="NVIDIA GeForce RTX 3060 Laptop GPU" libdirs=ollama,cuda_v12 driver=13.0 pci_id=0000:01:00.0 type=discrete total="6.0 GiB" available="5.0 GiB"
time=2025-11-11T19:01:42.195+08:00 level=INFO source=routes.go:1619 msg="entering low vram mode" "total vram"="6.0 GiB" threshold="20.0 GiB"
time=2025-11-11T19:01:45.311+08:00 level=INFO source=server.go:400 msg="starting runner" cmd="E:\\Ollama\\ollama.exe runner --ollama-engine --port 6115"
time=2025-11-11T19:01:45.524+08:00 level=INFO source=cpu_windows.go:148 msg=packages count=1
time=2025-11-11T19:01:45.524+08:00 level=INFO source=cpu_windows.go:195 msg="" package=0 cores=8 efficiency=0 threads=16
time=2025-11-11T19:01:45.591+08:00 level=INFO source=server.go:215 msg="enabling flash attention"
time=2025-11-11T19:01:45.592+08:00 level=INFO source=server.go:400 msg="starting runner" cmd="E:\\Ollama\\ollama.exe runner --ollama-engine --model E:\\Ollama\\models\\blobs\\sha256-a3de86cd1c132c822487ededd47a324c50491393e6565cd14bafa40d0b8e686f --port 6122"
time=2025-11-11T19:01:45.612+08:00 level=INFO source=server.go:653 msg="loading model" "model layers"=37 requested=-1
time=2025-11-11T19:01:45.612+08:00 level=INFO source=server.go:658 msg="system memory" total="15.8 GiB" free="4.9 GiB" free_swap="6.0 GiB"
time=2025-11-11T19:01:45.612+08:00 level=INFO source=server.go:665 msg="gpu memory" id=GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 library=CUDA available="4.6 GiB" free="5.0 GiB" minimum="457.0 MiB" overhead="0 B"
time=2025-11-11T19:01:45.656+08:00 level=INFO source=runner.go:1349 msg="starting ollama engine"
time=2025-11-11T19:01:45.667+08:00 level=INFO source=runner.go:1384 msg="Server listening on 127.0.0.1:6122"
time=2025-11-11T19:01:45.678+08:00 level=INFO source=runner.go:1222 msg=load request="{Operation:fit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:8 GPULayers:37[ID:GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 Layers:37(0..36)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-11-11T19:01:45.703+08:00 level=INFO source=ggml.go:136 msg="" architecture=qwen3 file_type=Q4_K_M name="Qwen3 8B" description="" num_tensors=399 num_key_values=29
load_backend: loaded CPU backend from E:\Ollama\lib\ollama\ggml-cpu-icelake.dll
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060 Laptop GPU, compute capability 8.6, VMM: yes, ID: GPU-52b31a98-e414-b31b-363a-f98b19c51bb6
load_backend: loaded CUDA backend from E:\Ollama\lib\ollama\cuda_v12\ggml-cuda.dll
time=2025-11-11T19:01:45.816+08:00 level=INFO source=ggml.go:104 msg=system CPU.0.SSE3=1 CPU.0.SSSE3=1 CPU.0.AVX=1 CPU.0.AVX2=1 CPU.0.F16C=1 CPU.0.FMA=1 CPU.0.BMI2=1 CPU.0.AVX512=1 CPU.0.AVX512_VBMI=1 CPU.0.AVX512_VNNI=1 CPU.0.LLAMAFILE=1 CPU.1.LLAMAFILE=1 CUDA.0.ARCHS=500,520,600,610,700,750,800,860,890,900,1200 CUDA.0.USE_GRAPHS=1 CUDA.0.PEER_MAX_BATCH_SIZE=128 compiler=cgo(clang)
time=2025-11-11T19:01:46.044+08:00 level=INFO source=runner.go:1222 msg=load request="{Operation:fit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:8 GPULayers:34[ID:GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 Layers:34(2..35)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-11-11T19:01:46.082+08:00 level=INFO source=runner.go:1222 msg=load request="{Operation:alloc LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:8 GPULayers:34[ID:GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 Layers:34(2..35)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=runner.go:1222 msg=load request="{Operation:commit LoraPath:[] Parallel:1 BatchSize:512 FlashAttention:true KvSize:4096 KvCacheType: NumThreads:8 GPULayers:34[ID:GPU-52b31a98-e414-b31b-363a-f98b19c51bb6 Layers:34(2..35)] MultiUserCache:false ProjectorPath: MainGPU:0 UseMmap:false}"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=ggml.go:482 msg="offloading 34 repeating layers to GPU"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=ggml.go:486 msg="offloading output layer to CPU"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=ggml.go:494 msg="offloaded 34/37 layers to GPU"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:212 msg="model weights" device=CUDA0 size="3.8 GiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:217 msg="model weights" device=CPU size="1.0 GiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:223 msg="kv cache" device=CUDA0 size="544.0 MiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:228 msg="kv cache" device=CPU size="32.0 MiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:234 msg="compute graph" device=CUDA0 size="185.0 MiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:239 msg="compute graph" device=CPU size="8.0 MiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=device.go:244 msg="total memory" size="5.6 GiB"
time=2025-11-11T19:01:46.322+08:00 level=INFO source=sched.go:500 msg="loaded runners" count=1
time=2025-11-11T19:01:46.322+08:00 level=INFO source=server.go:1251 msg="waiting for llama runner to start responding"
time=2025-11-11T19:01:46.323+08:00 level=INFO source=server.go:1285 msg="waiting for server to become available" status="llm server loading model"
time=2025-11-11T19:01:48.827+08:00 level=INFO source=server.go:1289 msg="llama runner started in 3.22 seconds"
[GIN] 2025/11/11 - 19:01:53 | 500 |    8.0343688s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2025/11/11 - 19:02:01 | 500 |    8.0124622s |       127.0.0.1 | POST     "/v1/chat/completions"

<img width="2560" height="1080" alt="Image" src="https://github.com/user-attachments/assets/24d8b763-75c1-48c1-b7a1-8064e10805bb" />

**Comment by Nuo27** [comment]
@ABC-0101 看上去并不是插件的问题，接口返回的也是500。你看看ollama run能不能跑，要么是模型没有被load，要么就是新qwen的flash attention的问题，可以去ollama仓库看看有没有同样问题

**Comment by ABC-0101** [comment]
<img width="869" height="90" alt="Image" src="https://github.com/user-attachments/assets/f109af61-738e-4eb1-9ef7-cd61b05c7142" />

<img width="1174" height="355" alt="Image" src="https://github.com/user-attachments/assets/1a43195b-e05a-4cb3-945f-e2f4d331700c" />

**Comment by Nuo27** [comment]
@ABC-0101 尝试用curl写一个测试的请求看看你的模型有没有正确回复，还有可能是请求超时
可以参考
`curl -X POST http://localhost:11434/v1/chat/completions ^
-H "Content-Type: application/json" ^
-d "{\"model\": \"qwen3:8b\", \"messages\": [{\"role\": \"user\", \"content\": \"Hello world\"}]}"
`

**Comment by ABC-0101** [comment]
curl -X POST http://localhost:11434/v1/chat/completions ^ -H "Content-Type: application/json" ^ -d "{\"model\": \
"qwen3:8b\", \"messages\": [{\"role\": \"user\", \"content\": \"Hello world\"}]}"
{"id":"chatcmpl-915","object":"chat.completion","created":1762864706,"model":"qwen3:8b","system_fingerprint":"fp_ollama","choices":[{"index":0,"message":{"role":"assistant","content":"Hello! 😊 How can I assist you today? Whether you have questions, need help with something, or just want to chat, I'm here for you!","reasoning":"Okay, the user just said \"Hello world\". That's a common greeting, maybe they're testing if I'm working or just starting a conversation. I should respond in a friendly and open manner.\n\nLet me think about how to reply. I need to be welcoming and invite them to ask questions or share what they need help with. Maybe something like, \"Hello! How can I assist you today?\" That's straightforward and encourages them to elaborate.\n\nWait, should I add more personality? Maybe a smiley emoji to keep it light. Yeah, that could make the response feel more approachable. Let me go with that. Also, make sure the tone is positive and ready to help. Alright, that should work.\n"},"finish_reason":"stop"}],"usage":{"prompt_tokens":12,"completion_tokens":183,"total_tokens":195}}

**Comment by Nuo27** [comment]
@ABC-0101 
edited: 我刚刚下载并测试了qwen3:8b ollama0.12.10，是可以正常使用的
**确保你打开了账户设置，保存了model info，或者直接修改DEFAULT_MODEL_NAME变量为你的默认fallback模型名** 
目前默认fallback的模型是qwen3:14b，如果你的model info没有成功保存，插件会尝试调用14b
可以在ServerLogin方法里加上 `HostOpenConsole();` 来打开控制台查看日志
> 如果curl能成功的话，那可能是模型账户信息没有配置到。你可以检查一下你的模型配置信息吗_

**Comment by ABC-0101** [comment]
设置默认qwen3:8b还是不行
--------PotPlayer's AngelScript console--------
Model information retrieved successfully
Parameters:
  stop                           "<|im_start|>"
  stop                           "<|im_end|>"
  temperature                    0.6
  top_k                          20
  top_p                          0.95
  repeat_penalty                 1
Model Info:
  general.architecture: qwen3
  general.basename: Qwen3
  general.file_type: 15
  general.license: apache-2.0
  general.parameter_count: 8.19074e+09
  general.quantization_version: 2
  general.size_label: 8B
  general.type: model
  qwen3.attention.head_count: 32
  qwen3.attention.head_count_kv: 8
  qwen3.attention.key_length: 128
  qwen3.attention.layer_norm_rms_epsilon: 1e-06
  qwen3.attention.value_length: 128
  qwen3.block_count: 36
  qwen3.context_length: 40960
  qwen3.embedding_length: 4096
  qwen3.feed_forward_length: 12288
  qwen3.rope.freq_base: 1000000
  tokenizer.ggml.add_bos_token: false
  tokenizer.ggml.bos_token_id: 151643
  tokenizer.ggml.eos_token_id: 151645
  tokenizer.ggml.merges: null
  tokenizer.ggml.model: gpt2
  tokenizer.ggml.padding_token_id: 151643
  tokenizer.ggml.pre: qwen2
  tokenizer.ggml.token_type: null
  tokenizer.ggml.tokens: null

Successfully configured Ollama translation plugin

Model: qwen3:8b

Native thinking support: Yes

The script was aborted before it could finish. Probably it timed out.

<img width="1235" height="718" alt="Image" src="https://github.com/user-attachments/assets/f7297263-73c3-488a-9505-612106eba005" />

<img width="1392" height="680" alt="Image" src="https://github.com/user-attachments/assets/97319a1f-2d6b-4b99-a907-8cbf76081802" />

**Comment by Nuo27** [comment]
@ABC-0101 
> The script was aborted before it could finish. Probably it timed out.

很可能是 Ollama的请求超时，由于 PotPlayer 本身没有提供 HTTP 请求相关的文档，而你的模型每次推理需要 8 秒，很可能是因为模型响应太慢导致的请求超时被中止

> Model information retrieved successfully

问题不是插件造成的，因为你的 curl 请求是成功的，模型列表和信息也正常请求读取到了，那只能是请求超时了

_甚至有可能翻译功能本身还是可以用的，只是速度太慢而已_

建议你使用响应更快的模型，毕竟如果花 8 秒才能完成一次单行翻译对实时字幕翻译来说不够快，我感觉至少能达到20-30t/s左右的速度才能保证实时翻译的流畅

_qwen3是moe架构并且有instruct版本的，对于纯文本生成任务跳过推理过程也并不怎么影响翻译精度_

**Comment by ABC-0101** [comment]
换回1.12.1就正常 延迟也低
time=2025-11-12T21:17:53.066+08:00 level=INFO source=server.go:1289 msg="llama runner started in 3.52 seconds"
[GIN] 2025/11/12 - 21:17:54 | 200 |    5.5272724s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2025/11/12 - 21:21:20 | 200 |    1.4751078s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2025/11/12 - 21:21:22 | 200 |    1.3713269s |       127.0.0.1 | POST     "/v1/chat/completions"
[GIN] 2025/11/12 - 21:21:23 | 200 |    1.5040187s |       127.0.0.1 | POST     "/v1/chat/completions"

**Comment by Nuo27** [comment]
@ABC-0101
qwen3有过一次版本更新，调整了框架，并且ollama 在 0.12.4 版本之后默认启用了flash attention，你的serve日志也显示该功能已启用。你可以对比一下 0.12.1版本的日志，确认一下是不是flash attention的问题
因为我的环境在 0.12.10 下运行 qwen3:8b是正常的，复现不了你的问题。你也可以尝试重新pull一下qwen3:8b，确认一下是否是因框架缓存未更新导致的

> 换回1.12.1就正常 延迟也低

问题出在ollama本身，如果你在ollama仓库找不到类似的issue也可以先用回老版本，等到ollama他们修了再更新
_要是不用新模型或者什么新功能其实也没有更新的必要，越新越臃肿_ :/

**Comment by ABC-0101** [comment]
把flash attention关了也不行

**Comment by Nuo27** [comment]
@ABC-0101 
ollama更新最好执行清洁安装来确保跑的是新的lib
如果你测试在0.12.1跑是100%gpu的话，而到了0.12.10有cpu介入的话 可能会有各种各样的原因，这个还是去ollama官方仓库提个issue并提交一下你的server log给他们看吧，你可以link回这个issue作reference

**Comment by Nuo27** [comment]
@ABC-0101 
我已把插件更新至 v2.1，并基于 Ollama 0.13.0 版本测试了多个模型，你之前反馈的问题应该已得到修复。
建议你测试一下这个版本

**Comment by ABC-0101** [comment]
正常工作了
